@AwesomeCompany_HostAddress = http://localhost:5096

GET {{AwesomeCompany_HostAddress}}/todos/
Accept: application/json

###

GET {{AwesomeCompany_HostAddress}}/todos/1
Accept: application/json

###

GET {{AwesomeCompany_HostAddress}}/employee/all

###
GET {{AwesomeCompany_HostAddress}}/employee/120
Accept: application/json

PUT {{AwesomeCompany_HostAddress}}/employee/increase-salaries?companyId=1
